In [6]:
#Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.metrics import classification_report, confusion_matrix

In [7]:
#Dataset
churn_csv="C:\\Users\\hp\\Downloads\\WA_Fn-UseC_-Telco-Customer-Churn.csv"
df = pd.read_csv(churn_csv)
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [8]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

In [9]:
df.shape

(7043, 21)

In [10]:
print(df['Churn'].value_counts())

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [11]:
#Data Preprocessing
# Remove customerID
df.drop('customerID', axis=1, inplace=True)

In [12]:
#TotalCharges to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].mean())

In [13]:
#Categorical variable
for column in df.columns:
    if df[column].dtype == 'object':
        le = LabelEncoder()
        df[column] = le.fit_transform(df[column])

In [14]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1990.50,0
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,7362.90,0
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,346.45,0
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,306.60,1
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,6844.50,0

In [15]:
#Features and target
X = df.drop('Churn', axis=1)
y = df['Churn']

In [16]:
#Scale features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [17]:
#Train - Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
#Model
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=X_train.shape[1]))
model.add(Dropout(0.3))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

c:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [19]:
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - accuracy: 0.6845 - loss: 0.5844 - val_accuracy: 0.7808 - val_loss: 0.4701
Epoch 2/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7621 - loss: 0.4971 - val_accuracy: 0.7995 - val_loss: 0.4390
Epoch 3/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7661 - loss: 0.4777 - val_accuracy: 0.7986 - val_loss: 0.4296
Epoch 4/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7710 - loss: 0.4658 - val_accuracy: 0.7933 - val_loss: 0.4258
Epoch 5/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7781 - loss: 0.4609 - val_accuracy: 0.7977 - val_loss: 0.4219
Epoch 6/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7815 - loss: 0.4527 - val_accuracy: 0.7977 - val_loss: 0.4199
Epoch 7/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7890 - loss: 0.4495 - val_accuracy: 0.8030 - val_loss: 0.4180
Epoch 8/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7839 - loss: 0.4515 - val_accuracy: 0.8004 - val_loss: 0.4161
Epoch 9/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7868 - loss: 0.4473 - val_accuracy: 0.8004 - val_loss: 0.4148
Epoch 10/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7879 - loss: 0.4472 - val_accuracy: 0.7995 - val_loss: 0.4139
Epoch 11/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.7901 - loss: 0.4455 - val_accuracy: 0.8021 - val_loss: 0.4134
Epoch 12/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7912 - loss: 0.4377 - val_accuracy: 0.8021 - val_loss: 0.4131
Epoch 13/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7930 - loss: 0.4367 - val_accuracy: 0.8048 - val_loss: 0.4125
Epoch 14/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7914 - loss: 0.4345 - val_accuracy: 0.8092 - val_loss: 0.4127
Epoch 15/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7948 - loss: 0.4377 - val_accuracy: 0.8030 - val_loss: 0.4120
Epoch 16/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7943 - loss: 0.4367 - val_accuracy: 0.8101 - val_loss: 0.4119
Epoch 17/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7892 - loss: 0.4388 - val_accuracy: 0.8083 - val_loss: 0.4105
Epoch 18/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.7939 - loss: 0.4371 - val_accuracy: 0.8101 - val_loss: 0.4095
Epoch 19/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7879 - loss: 0.4411 - val_accuracy: 0.8057 - val_loss: 0.4105
Epoch 20/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7954 - loss: 0.4378 - val_accuracy: 0.8083 - val_loss: 0.4102
Epoch 21/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7905 - loss: 0.4362 - val_accuracy: 0.8075 - val_loss: 0.4098
Epoch 22/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8023 - loss: 0.4275 - val_accuracy: 0.8083 - val_loss: 0.4099
Epoch 23/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7930 - loss: 0.4338 - val_accuracy: 0.8057 - val_loss: 0.4108
Epoch 24/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7910 - loss: 0.4353 - val_accuracy: 0.8101 - val_loss: 0.4092
Epoch 25/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7934 - loss: 0.4351 - val_accuracy: 0.8066 - val_loss: 0.4093
Epoch 26/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7959 - loss: 0.4331 - val_accuracy: 0.8092 - val_loss: 0.4090
Epoch 27/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8012 - loss: 0.4260 - val_accuracy: 0.8119 - val_loss: 0.4077
Epoch 28/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7972 - loss: 0.4258 - val_accuracy: 0.8110 - val_loss: 0.4083
Epoch 29/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7945 - loss: 0.4279 - val_accuracy: 0.8101 - val_loss: 0.4081
Epoch 30/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8003 - loss: 0.4280 - val_accuracy: 0.8128 - val_loss: 0.4094
Epoch 31/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7963 - loss: 0.4290 - val_accuracy: 0.8092 - val_loss: 0.4101
Epoch 32/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7959 - loss: 0.4347 - val_accuracy: 0.8101 - val_loss: 0.4099
Epoch 33/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8010 - loss: 0.4232 - val_accuracy: 0.8101 - val_loss: 0.4099
Epoch 34/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7957 - loss: 0.4236 - val_accuracy: 0.8119 - val_loss: 0.4098
Epoch 35/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7985 - loss: 0.4293 - val_accuracy: 0.8057 - val_loss: 0.4099
Epoch 36/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8030 - loss: 0.4220 - val_accuracy: 0.8075 - val_loss: 0.4090
Epoch 37/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8036 - loss: 0.4187 - val_accuracy: 0.8057 - val_loss: 0.4102
Epoch 38/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7992 - loss: 0.4210 - val_accuracy: 0.8101 - val_loss: 0.4101
Epoch 39/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8003 - loss: 0.4236 - val_accuracy: 0.8119 - val_loss: 0.4106
Epoch 40/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8012 - loss: 0.4211 - val_accuracy: 0.8066 - val_loss: 0.4106
Epoch 41/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8021 - loss: 0.4160 - val_accuracy: 0.8119 - val_loss: 0.4117
Epoch 42/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7983 - loss: 0.4174 - val_accuracy: 0.8057 - val_loss: 0.4101
Epoch 43/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8028 - loss: 0.4167 - val_accuracy: 0.8048 - val_loss: 0.4106
Epoch 44/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8014 - loss: 0.4278 - val_accuracy: 0.8039 - val_loss: 0.4119
Epoch 45/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7992 - loss: 0.4202 - val_accuracy: 0.8012 - val_loss: 0.4129
Epoch 46/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8059 - loss: 0.4161 - val_accuracy: 0.7995 - val_loss: 0.4127
Epoch 47/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8014 - loss: 0.4218 - val_accuracy: 0.8012 - val_loss: 0.4134
Epoch 48/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8025 - loss: 0.4216 - val_accuracy: 0.8057 - val_loss: 0.4141
Epoch 49/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8021 - loss: 0.4193 - val_accuracy: 0.8066 - val_loss: 0.4126
Epoch 50/50
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8072 - loss: 0.4173 - val_accuracy: 0.8083 - val_loss: 0.4124

In [20]:
#Accuracy
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.2f}")

#predictions
y_pred = (model.predict(X_test) > 0.5).astype("int32")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8091 - loss: 0.4078
Test Accuracy: 0.81
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
              precision    recall  f1-score   support

           0       0.84      0.92      0.88      1036
           1       0.69      0.51      0.59       373

    accuracy                           0.81      1409
   macro avg       0.76      0.71      0.73      1409
weighted avg       0.80      0.81      0.80      1409

[[949  87]
 [182 191]]

In [21]:
#New Data
new_customer = np.array([[
    0,   # gender (0=Female,1=Male)
    0,   # SeniorCitizen
    1,   # Partner
    0,   # Dependents
    1,   # tenure (e.g., 1-72 months)
    1,   # PhoneService
    0,   # MultipleLines
    1,   # InternetService
    0,   # OnlineSecurity
    1,   # OnlineBackup
    0,   # DeviceProtection
    1,   # TechSupport
    0,   # StreamingTV
    1,   # StreamingMovies
    1,   # Contract
    0,   # PaperlessBilling
    1,   # PaymentMethod
    50.0,# MonthlyCharges
    200.0# TotalCharges
]])
new_customer = scaler.transform(new_customer)  # Scale like training data
churn_prob = model.predict(new_customer)[0][0]

print(f"\nChurn Probability for New Customer: {churn_prob:.2f}")
print("Prediction:", "Churn" if churn_prob > 0.5 else "No Churn")

c:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

Churn Probability for New Customer: 0.20
Prediction: No Churn